apiVersion: v1
kind: Pod
metadata:
  name: web-app-1
  labels:
    app: web-app
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: web-app-2
  labels:
    app: web-app
spec:
  containers:
  - name: httpd-container
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80