apiVersion: v1
kind: Pod
metadata:
  name: nginx-volume-mount
  labels:
    app: nginx-volume-mount
spec:
  volumes:
    - name: "htmlvol"
      hostPath:
          path: "/home/html"
  containers:
  - name: nginx-container
    image: nginx:1.17.6
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
    volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: "htmlvol"
